### ISSUE TITLE
Build for 5.15-24.08

### ISSUE THREAD

**Issue by freddyw** [flathub/org.kde.WaylandDecoration.QAdwaitaDecorations#18]
Flatpak org.kde.Sdk 5.15-24.08 runtime is now available
(https://discuss.kde.org/t/flatpak-org-kde-sdk-5-15-24-08-runtime-is-now-available/25313)

Would love to see a build for version 5.15-24.08.

**Comment by grulja** [comment]
Done https://github.com/flathub/org.kde.WaylandDecoration.QAdwaitaDecorations/tree/branch/5.15-24.08.
