### ISSUE TITLE
Broken window titlebar

### ISSUE THREAD

**Issue by nikich768** [flathub/org.kde.WaylandDecoration.QAdwaitaDecorations#3]
![Untitled](https://github.com/flathub/org.kde.WaylandDecoration.QAdwaitaDecorations/assets/147100809/3f15d3c5-e3e9-477e-98d6-7c227b925287)

**Comment by Hasshu** [comment]
This has been fixed by a recent update, I believe.

**Comment by tsdgeos** [comment]
Marked as closed as per last commenter
