### ISSUE TITLE
Build for 5.15-23.08

### ISSUE THREAD

**Issue by cgutman** [flathub/org.kde.WaylandDecoration.QAdwaitaDecorations#8]
I'm aiming to bump my app to use the org.kde.Platform//5.15-23.08 runtime, but this leads to loss of native Adwaita-style decorations. I'd appreciate a build of the QAdwaitaDecorations plugin for 5.15-23.08 to fix that.

**Comment by grulja** [comment]
I created "branch/5.15-23.08" branch right now, with updated decorations to the latest version.
